# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  checks:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/core
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
        cache-dependency-path: packages/core/package-lock.json
    - run: npm ci
    - run: npm run prettier:ci
    - run: npm run eslint:ci
    - run: npm run build-storybook
    - run: npm run docs
    - run: npm run test:ci
    - run: npm run build
